apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-grade-submission-api
  labels:
    app: grade-submission
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.service.targetPort }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: grade-submission
    release: {{ .Release.Name }}