apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: hashicorp/http-echo
        args:
        - "-text=Welcome to your Kubernetes cluster running with ArgoCD, next step is learning rbac in kubernetes"
        ports:
        - containerPort: 5678
